apiVersion: v1
kind: Service
metadata:
  name: {{.app}}
spec:
  selector:
    app: {{.app}}
    tier: {{.tier}}
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: {{.app}}
    tier: {{.tier}}
  name: {{.app}}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{.app}}
        tier: {{.tier}}
    spec:
      containers:
      - image: {{.image}}
        # imagePullPolicy: IfNotPresent
        name: {{.app}}
        ports:
        - containerPort: 3000
          protocol: TCP
      terminationGracePeriodSeconds: 30
  minReadySeconds: 20
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
    type: RollingUpdate