query allCollaborations {
  allCollaborations(sortBy: [publishTime_DESC], first: 10, where: { state: published }) {
    id
    title
    description
    heroImage {
      urlOriginal
      urlDesktopSized
      urlTabletSized
      urlMobileSized
    }
    collabLink
    achvLink
    requireTime
    progress
    endTime
  }
}
