query latestPosts {
  latestPosts: allPosts(
    first: 4
    where: { state: published, style_in: [news, report] }
    sortBy: [publishTime_DESC]
  ) {
    id
    slug
    title: name
    style
    heroImage {
      urlMobileSized
    }
    ogImage {
      urlMobileSized
    }
  }
}
