query homePageOnServer {
  editorChoices: allEditorChoices(
    sortBy: [sortOrder_ASC, publishTime_DESC]
    first: 5
    where: { state: published }
  ) {
    id
    title: name
    link
    heroImage {
      urlTabletSized
    }
  }

  latestPosts: allPosts(
    first: 5
    where: { state: published, style_in: [news, report] }
    sortBy: [publishTime_DESC]
  ) {
    id
    slug
    title: name
    style
    heroImage {
      urlTabletSized
    }
    ogImage {
      urlTabletSized
    }
    publishTime
  }
}
