query latestPosts($first: Int! = 3) {
  latestPosts: allPosts(
    first: $first,
    where: { state: published, style_in: [news, report] },
    sortBy: [publishTime_DESC]
  ) {
    id
    title
    publishTime
    style
    heroImage {
      title
      urlMobileSized
      urlTabletSized
    }
    ogImage {
      title
      urlMobileSized
      urlTabletSized
    }
    heroCaption
  }
}
