query report($id: ID!) {
  post: Post(where: { id: $id }) {
    slug
    title: name
    heroImage {
      urlOriginal
    }
    contentApiData
    ogTitle
    ogDescription
    ogImage {
      urlOriginal
    }
    tags {
      name
    }
    publishTime
    updatedAt
  }
}

query news($id: ID!) {
  post: Post(where: { id: $id }) {
    title: name
    heroImage {
      name
      urlMobileSized
      urlDesktopSized
    }
    contentHtml
    ogTitle
    ogDescription
    ogImage {
      name
      urlMobileSized
      urlDesktopSized
    }
    tags {
      name
    }
    publishTime
    updatedAt
  }
}
