query Post($id: ID!) {
  post: Post(where: { id: $id }) {
    publishTime
    title
    heroImage {
      title
      urlTabletSized
    }
    heroCaption
    contentHtml
    ogTitle
    ogDescription
    ogImage {
      title
      urlTabletSized
    }
    wordCount
    updatedAt
    tags {
      name
    }
  }
}
